### ISSUE TITLE
can we put horizontal rules / dividers / visual distinction somewhere here to make them more distinguishable http://screencast.com/t/A3mCV0xbyB

### ISSUE THREAD

**Issue by LimeCuda** [BeardedGinger/adsense-owner-author-split#6]

**Comment by BeardedGinger** [comment]
Good idea. Taking a note from the other genesis settings pages I decided to break them out into their own metaboxes
![screen shot 2016-05-18 at 7 31 01 pm](https://cloud.githubusercontent.com/assets/3269229/15378134/c3b2385a-1d2e-11e6-8e8b-4bfb20f2d05f.png)

**Comment by LimeCuda** [comment]
Perfect

On Wednesday, May 18, 2016, Josh Mallard notifications@github.com wrote:

> Good idea. Taking a note from the other genesis settings pages I decided
> to break them out into their own metaboxes
> [image: screen shot 2016-05-18 at 7 31 01 pm]
> https://cloud.githubusercontent.com/assets/3269229/15378134/c3b2385a-1d2e-11e6-8e8b-4bfb20f2d05f.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/BeardedGinger/adsense-owner-author-split/issues/6#issuecomment-220188079

## 

## 

Blake Imeson
_LimeCuda.com http://limecuda.com/ | *_724.870.4742*

http://limecuda.com/
